import type { Metadata } from "next";
import "../globals.css";
import Provider from "@/components/provider";
import { Toaster } from "@/components/ui/sonner";
import AccountSidebar from "@/components/page-layout/account/sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="w-dvw h-dvh flex">
            <Provider>
                <AccountSidebar />
                {children}
            </Provider>
            <Toaster />
        </main>
    );
}
