import type { Metadata } from "next";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import AccountSidebar from "@/components/account/sidebar";
import { Providers } from "../providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="w-dvw h-dvh flex">
            <Providers>
                <AccountSidebar />
                {children}
            </Providers>
            <Toaster />
        </main>
    );
}
